apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-pv-volume
  labels:
    type: local
    app: spring
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
      - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spring-pv-claim
  labels:
    app: spring
spec:
  storageClassName: manual
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 5Gi